inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2.2
  UseCache: true
  NewCops: enable
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'spec/**/*'
    - 'Gemfile'
    - 'config/initializers/rack_attack.rb'
    - 'script/single_use/**/*'

Layout:
  # let prettier take care of it
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 25

# Many AbcSize in the 50-100 range.
Metrics/AbcSize:
  Max: 80

Metrics/ClassLength:
  # Enabled: false

Metrics/BlockLength:
  # Enabled: false

Metrics/MethodLength:
  # Enabled: false

Metrics/ModuleLength:
  Max: 200

Metrics/PerceivedComplexity:
  Max: 20

# Trade off between obvious class searching and tons of indentation. leaving it as is.
Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

# This is a concise way to force true/false instead of returning objects or who knows what and making other people deal with it
Style/DoubleNegation:
  Enabled: false

# separate every three digits in a zip code/phone number? gtfo.
Style/NumericLiterals:
  Enabled: false

# is_ and has_ provide extra information and were a style at one point
Naming/PredicateName:
  # Enabled: false
  # Let's try it and see what happens

# we have too many db fields like address_1 and population_women_13_to_44
Naming/VariableNumber:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

# TODO add string literals
Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false
  # let prettier handle it

Style/WordArray:
  Enabled: false
  # let prettier handle it

Style/MultilineBlockChain:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Rails/I18nLazyLookup:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false
