command_definitions:
  - name: uncommitted_git_changes
    shell: 'git diff --quiet --exit-code'
    root_dir: "./"
    if: "shell command that returns exit code (0 means run this command) eg bundle list | grep 'gem_name'"
    env:
      VAR_NAME: "test"

# always run, in addition to parallel_commands in the project specific yml
parallel_commands:
