command_definitions:
  "uncommitted git changes":
    shell: "git diff --quiet --exit-code"

  "rspec":
    shell: "bundle exec rspec"
    if: "bundle list | grep 'rspec'"

  "brakeman":
    shell: "bundle exec brakeman --run-all-checks --no-pager --quiet"
    if: "bundle list | grep 'brakeman'"

  "bundle audit":
    shell: "bundle exec bundle-audit --update"
    if: "test -f Gemfile.lock"

  "bundle leak":
    shell: "bundle leak --update"
    if: "test -f Gemfile.lock"

  "npm audit":
    shell: "npm audit --audit-level=high"
    if: "test -f package-lock.json"

  "yarn audit":
    shell: "yarn audit"
    if: "test -f yarn.lock"

  "jest":
    shell: "npm run | grep -q ' jest' && npm run jest || npx jest"
    if: "npm list jest"

  "rubocop":
    shell: "bundle exec rubocop"
    if: "test -f Gemfile.lock"

  "prettier":
    shell: "npm run | grep -q ' prettier' && npm run prettier || npx prettier --ignore-unknown"
    if: "npm list prettier"

  "yaml lint":
    shell: "npx yamllint **/*.(yaml|yml) --ignore-dir=.node_modules"
    if: "npm list yamllint"


# always run, in addition to parallel_commands in the project specific yml
parallel_commands:
  - name: brakeman
    shell: 'echo "pretend Im running bundle exec brakeman" && sleep 6 && echo "..." && sleep 6'
  # - bundle audit
  # - bundle leak
  - name: jest
    shell: echo "pretend im running jest"
  # prettier:
  # rspec:
  # rubocop:
  # - uncommitted git changes
  # - yaml lint
