# command_definitions:
#   - name: uncommitted git changes
#     shell: "git diff --quiet --exit-code"

#   - name: rspec
#     shell: "bundle exec rspec"
#     if: "bundle list | grep 'rspec'"

#   - name: brakeman
#     shell: "bundle exec brakeman --run-all-checks --no-pager --quiet"
#     if: "test -f Gemfile.lock"

#   - name: bundle audit
#     shell: "bundle exec bundle-audit --update"
#     if: "test -f Gemfile.lock"

#   - name: bundle leak
#     shell: "bundle leak --update"
#     if: "test -f Gemfile.lock"

#   - name: npm audit
#     shell: "npm audit --audit-level=high"
#     if: "test -f package-lock.json"

#   - name: prettier
#     # define a custom script in package.json or fallback to the default command
#     shell: "npm run | grep -q ' prettier' && npm run prettier || npx prettier --ignore-unknown"

#   - name: jest
#     # define a custom script in package.json or fallback to the default command
#     shell: "npm run | grep -q ' jest' && npm run jest || npx jest"

#   - name: rubocop
#     shell: "bundle exec rubocop"
#     if: "test -f Gemfile.lock"

#   - name: yaml lint
#     shell: "npx yamllint **/*.(yaml|yml) --ignore-dir=.node_modules"

command_definitions:
  "uncommitted git changes":
    shell: "git diff --quiet --exit-code"

  "rspec":
    shell: "bundle exec rspec"
    if: "bundle list | grep 'rspec'"

  "brakeman":
    shell: "bundle exec brakeman --run-all-checks --no-pager --quiet"
    if: "test -f Gemfile.lock"

  "bundle audit":
    shell: "bundle exec bundle-audit --update"
    if: "test -f Gemfile.lock"

  "bundle leak":
    shell: "bundle leak --update"
    if: "test -f Gemfile.lock"

  "npm audit":
    shell: "npm audit --audit-level=high"
    if: "test -f package-lock.json"

  "prettier":
    shell: "npm run | grep -q ' prettier' && npm run prettier || npx prettier --ignore-unknown"

  "jest":
    shell: "npm run | grep -q ' jest' && npm run jest || npx jest"

  "rubocop":
    shell: "bundle exec rubocop"
    if: "test -f Gemfile.lock"

  "yaml lint":
    shell: "npx yamllint **/*.(yaml|yml) --ignore-dir=.node_modules"


# always run, in addition to parallel_commands in the project specific yml
parallel_commands:
  - name: brakeman
    shell: 'echo "pretend Im running bundle exec brakeman"'
  # - bundle audit
  # - bundle leak
  - name: jest
    shell: echo "pretend im running jest"
  # prettier:
  # rspec:
  # rubocop:
  # - uncommitted git changes
  # - yaml lint
